print("Iremos definir a média da altura do tempo: ")
nt = input("O nome deles/time: ")
imprimir(" haverá somente 6 jogadores ")
alt1 = float(input("Me informe a altura do jogador 1: "))
alt2 = float(input("Me informe a altura do jogador 2: "))
alt3 = float(input("Me informe a altura do jogador 3: "))
alt4 = float(input("Me informe a altura do jogador 4: "))
alt5 = float(input("Me informe a altura do jogador 5: "))
alt6 = float(input("Me informe a altura do jogador 6: "))
media = (alt1 + alt2 + alt3 + alt4 + alt5 + alt6) / 6
print(f"A média das alturas dos jogadores é: {media}")