import random
alu1  = random.randint( “1,4“ )
alu2  = random.randint( “1,4“)
alu3  =  random.randint( “1,5“ )
alu4  =  random.randint(“1,5“ )
alu5  =  random.randint( “1,6“)
print( 'A ordem dos alunos sorteados é {}'.f )
print(“o 1”.f)
print(“o 2”.f)
print(“o 3”.f)
print(“o 4”.f)
print(“o 5”.f)
